apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: payments-service-postgres
  namespace: dev
spec:
  serviceName: payments-service-postgres
  replicas: 1
  selector:
    matchLabels:
      app: payments-service-postgres
  template:
    metadata:
      labels:
        app: payments-service-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:latest
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: payments
            - name: POSTGRES_USER
              value: root
            - name: POSTGRES_PASSWORD
              value: password
          volumeMounts:
            - name: paymentsservice-postgres-data
              mountPath: /home/nash/food-order-databases/payments-service-db/data
      volumes:
        - name: paymentsservice-postgres-data
          persistentVolumeClaim:
            claimName: paymentsservice-postgres-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paymentsservice-postgres-pvc
  namespace: dev
spec:
  accessModes:
    - ReadWriteOnce # ReadWriteOnce, the once means one node only can readwrite to volume
  resources:
    requests:
      storage: 1Gi  # Adjust the storage size as needed
---
apiVersion: v1
kind: Service
metadata:
  name: payments-service-postgres
  labels:
    app: payments-service-postgres
  namespace: dev
spec:
  ports:
    - name: gateway-port
      port: 5432
      targetPort: 5432
  type: ClusterIP
  selector:
    app: payments-service-postgres
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments-service-springboot
  labels:
    app: payments-service-springboot
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payments-service-springboot
  template:
    metadata:
      labels:
        app: payments-service-springboot
    spec:
      containers:
      - name: payments-service-springboot
        image: 192.168.20.222:8443/digitalbiohumans/poc/payments-service-springboot:0.0.5-SNAPSHOT
        imagePullPolicy: Always
        env:
          - name: EUREKA_INSTANCE_PREFER_IP_ADDRESS
            value: 'true'
          - name: SPRING_PROFILES_ACTIVE
            value: dev
          - name: SPRING_CLOUD_CONFIG_URI
            value: http://food-ordering-springboot-cloud-config:8888
        ports:
        - name: port-tcp
          containerPort: 8080
          protocol: TCP
        - name: port-udp
          containerPort: 8080
          protocol: UDP
          #TODO: Implement health checks
---
apiVersion: v1
kind: Service
metadata:
  name: payments-service-springboot
  labels:
    app: payments-service-springboot
  namespace: dev
spec:
  ports:
  - name: gateway-port
    port: 8080
    targetPort: 8080
  type: ClusterIP
  selector:
    app: payments-service-springboot
---